### ISSUE TITLE
Doesn't register in MacOS version

### ISSUE THREAD

**Issue by jmacie** [genkiinstruments/releases#1]
I have had Cosmos working for a year. I got a Genki email update notice on Dec.21 and I naturally I updated and it stopped working. After 2 Facebook posts and five emails to support I was linked here to github but this is dated October 21st and it doesn't work. I removed the vst and component extensions and uninstalled and reinstalled and it's the same it won't register

**Comment by multivac61** [comment]
I believe we have been in touch over email. Thank you for your patience in resolving this issue!

**Comment by jmacie** [comment]
Thank You, it is registering now I appreciate you helping me
