### ISSUE TITLE
release 0.13.0 is 'Apple Silicon' only

### ISSUE THREAD

**Issue by core-code** [genkiinstruments/releases#2]

**Comment by core-code** [comment]
<img width="271" alt="Screenshot 2024-04-25 at 00 24 03" src="https://github.com/genkiinstruments/releases/assets/1261954/dda2b2ff-ef3f-439e-81c1-d552c52e8c59">

**Comment by core-code** [comment]
is this on purpose?

**Comment by multivac61** [comment]
This is bug on our part. Apologies, we'll get it fixed asap.

**Comment by dingari** [comment]
Softwave 0.13.0 Universal macOS binary is now available on the [releases page](https://github.com/genkiinstruments/releases/releases/softwave). Thanks for reporting the issue!

**Comment by core-code** [comment]
thanks for the quick fix, i can confirm that it is resolved

**Comment by core-code** [comment]
(one thing to note: the new 0.13 release requires macOS 14, while previous releases (including the faulty ARM-only upload) only required macOS 10.11)

**Comment by dingari** [comment]
Hm, that's strange.

info.plist for the installed app shows

```
<key>LSMinimumSystemVersion</key>
<string>10.11</string>
```

Is this not the case for you?

**Comment by core-code** [comment]
i can confirm the LSMinimumSystemVersion entry, but it must have been compiled with a newer deployment SDK so it won't launch even on 13.0:
<img width="803" alt="Screenshot 2024-04-26 at 15 47 01" src="https://github.com/genkiinstruments/releases/assets/1261954/593d1a59-2788-4615-9e46-b0afcea54d2a">

**Comment by core-code** [comment]
the actual system requirements are the HIGHER one of (deploymentSDK, LSMinimumSystemVersion)

**Comment by dingari** [comment]
That seems to be true, `LC_VERSION_MIN_MACOSX` in the actual binary is wrong. We've fixed it now and updated the releases page.

**Comment by core-code** [comment]
confirmed fixed too, thanks
